apiVersion: apps/v1
  kind: Deployment
  metadata: name: basic-server
  labels:
    app: hello

  spec:
    selector:
      matchLabels:
        app: hello
        tier: web
    template:
      metadata:
        labels:
          app: hello
          tier: web
    spec: 
      containers:
      - name: basic-server
        image: ulicode/basic-server:v1
        ports:
        - containerPort: 8080
